/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lizd_ndk_jniUtils */

#ifndef _Included_com_example_lizd_ndk_jniUtils
#define _Included_com_example_lizd_ndk_jniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lizd_ndk_jniUtils
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lizd_ndk_jniUtils_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
