/* DO NOT EDIT THIS FILE - it is machine generated */
#include "syno_getkey.h"

#ifdef _DEMO_JNI_

#define MY_KEY "an~(shi|dem8od5ea3pkmimiaw3vsy!y"  //4 bytes shifting //about synodemo
#define COMM_KEY "*yigekaqi.shi*mei5ou)sm&gui6v^de" //7 bytes shifting
#define VERIFY_KEY ")i*kusua8nfaw6om#en5zi0jide(cesh"//10 bytes shifting //about synodemo
#define IMEIKEY "a*fjbhvajb2vaq(fgkadfba^dbhgk1af"

#define SECRETDATA "795B9FFEC3C29B5B32BBCE008A0239CB6A15509885A2B19E4D4B66D46CACB7F41047DC0FDCD239528E7179FDCCD5558E"
#define AAID "1#00#01"

#endif

#ifdef _ATWE_JNI_

#define MY_KEY "n%vfq~fzwwyuq2$@u88rtmm7qnnh^f$q"  //4 bytes shifting //about synodemo
#define COMM_KEY "*yigekaqi.shi*mei5ou)sm&gui6v^de" //7 bytes shifting
#define VERIFY_KEY "z37f0perz4fjeqao45&3(zde%32~f.ea"//10 bytes shifting //about synodemo
#define IMEIKEY "wr@mmze*fjn44fakrei&qmzrng8qmnyf"

#define SECRETDATA "795B9FFEC3C29B5B32BBCE008A0239CB6A15509885A2B19E4D4B66D46CACB7F41047DC0FDCD239528E7179FDCCD5558E"
#define AAID "1#05#01"

#endif

 
#define TAG "syno_getkey"
#define LOGI(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__)
 
 char* get_MY_KEY()
{
	return MY_KEY;
}

 char* get_COMM_KEY()
{
	return COMM_KEY;
}

 char* get_VERIFY_KEY()
{
	return VERIFY_KEY;
}

 char* get_IMEIKEY()
{
	return IMEIKEY;
}

 char* get_SECRETDATA()
{
	return SECRETDATA;
}

 char* get_AAID()
{
	//LOGI("return AAID %s",AAID);
	return AAID;
}